# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
