# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 20:41
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20180405_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='Upload',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='/data', location='/home/mcmillwh/BitBucket/batch_mobile/data'), upload_to='infiles/'),
        ),
    ]
