# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_conversion_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='ConvName',
            field=models.TextField(default=''),
        ),
    ]
