# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 19:01
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_conversion_convname'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='Output',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(base_url='/data', location='/home/mcmillwh/BitBucket/batch_mobile/data'), upload_to='outfiles/'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='RecordsIn',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversion',
            name='RecordsOut',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversion',
            name='TimeExecuted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='ConvName',
            field=models.TextField(default='None'),
        ),
    ]
